export const RoleKeys = [
  'platform.owner',
  'platform.admin',
  'platform.ops',
  'platform.finance',
  'platform.support',
  'platform.compliance',
  'platform.bd',
  'platform.readonly',
  'org.owner',
  'org.admin',
  'org.catalog',
  'org.pricing',
  'org.inventory',
  'org.sales',
  'org.fulfillment',
  'org.accounting',
  'org.support',
  'org.integrations',
  'org.readonly',
] as const;

export type RoleKey = (typeof RoleKeys)[number];

export const PermissionKeys = [
  'tenant.create',
  'tenant.manage',
  'tenant.read',
  'user.invite',
  'user.manage',
  'user.read',
  'role.assign',
  'role.read',
  'catalog.sku.create',
  'catalog.sku.update',
  'catalog.sku.publish',
  'catalog.sku.read',
  'inventory.adjust',
  'inventory.read',
  'pricing.update',
  'pricing.read',
  'orders.create',
  'orders.update',
  'orders.cancel',
  'orders.read',
  'orders.refund.initiate',
  'orders.refund.approve',
  'payout.create',
  'payout.release',
  'payout.read',
  'report.financial.download',
  'report.operations.download',
] as const;

export type PermissionKey = (typeof PermissionKeys)[number];
